/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:9d1b8376acbeccd3112bbe32886cc632:7352c4aafe2783cc9aad0a70dca9a1cc:884b009f6d6d1592ea2393b7587b3394$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Colliable_platform_1 = "colliable-platform-1";
		public const string Colliable_platform_2 = "colliable-platform-2";
		public const string Colliable_platform_3 = "colliable-platform-3";
		public const string Colliable_platform_4 = "colliable-platform-4";
	}
}