/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c501cc1eabbcc6a82671e5545d3a58b0:7a84e0e7274235ee26e938ecbcd82977:bfecdb9c4242e64fbb2698120b6ca3dd$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Coin_1 = "coin-1";
		public const string Coin_2 = "coin-2";
		public const string Coin_3 = "coin-3";
		public const string Coin_4 = "coin-4";
	}
}