/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:3fb0225991589a81c70fce969b3f6196:6d2dcdc4f09ecd96c2c51fd6236f1a86:d5e55719c68e8bf5f792a864666de9dd$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Green_koopas_walk_1 = "green-koopas-walk-1";
		public const string Green_koopas_walk_2 = "green-koopas-walk-2";
	}
}