/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:f6586b6b35f5775669d31919398bc252:1e9da01e716150f2330a23ac2586f31a:73689f2d402499fd845992479d689632$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Green_shell_1 = "green-shell-1";
		public const string Green_shell_2 = "green-shell-2";
		public const string Green_shell_3 = "green-shell-3";
		public const string Green_shell_4 = "green-shell-4";
	}
}