/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:ec2916cfb9a12c377964a79d471b6ee9:f1699f9b893a17465a2aaea0df77439e:3e53d5cf90d62a122956efd7b59b17b3$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Red_shell_1 = "red-shell-1";
		public const string Red_shell_2 = "red-shell-2";
		public const string Red_shell_3 = "red-shell-3";
		public const string Red_shell_4 = "red-shell-4";
	}
}