/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:ee68af1307e833094981e6a2e0f831c8:9c668542969026ee0c1f70a0bf4034be:6b9f6fa9e03db9a1bdd481a8d7b28aaa$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Red_koopas_walk_1 = "red-koopas-walk-1";
		public const string Red_koopas_walk_2 = "red-koopas-walk-2";
	}
}