/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:1e6904cf1f1d0fe7e84114105e029083:11d2b612ed5303a53bfaf53e49c4ff2f:90547f8b3bc08d8e4b8b068f11c1fd30$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Winged_red_koopas_11 = "winged-red-koopas-11";
		public const string Winged_red_koopas_22 = "winged-red-koopas-22";
		public const string Winged_red_koopas_33 = "winged-red-koopas-33";
		public const string Winged_red_koopas_44 = "winged-red-koopas-44";
	}
}