/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:48d4e1cffd9b1eb5e4557fb1325f6614:6890fb979d011c9b4303305fdfaac1c0:48422879ed0ec588b0aca02160533317$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Winged_green_koopas_11 = "winged-green-koopas-11";
		public const string Winged_green_koopas_22 = "winged-green-koopas-22";
		public const string Winged_green_koopas_33 = "winged-green-koopas-33";
		public const string Winged_green_koopas_44 = "winged-green-koopas-44";
	}
}