/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:fabf1ca7b239f65ca20f39e2d69400da:88c4246160ddd8809bb48363ab68d434:5aee1cc6c14cdb02f6f0fd1f39483107$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Bonus_pipe_bot_left = "bonus-pipe-bot-left";
		public const string Bonus_pipe_bot_right = "bonus-pipe-bot-right";
		public const string Bonus_pipe_top_left = "bonus-pipe-top-left";
		public const string Bonus_pipe_top_right = "bonus-pipe-top-right";
		public const string Bonus_platform = "bonus-platform";
		public const string Bush = "bush";
		public const string Cactus_left_side = "cactus-left-side";
		public const string Cactus_mid = "cactus-mid";
		public const string Cactus_outer_top_left = "cactus-outer-top-left";
		public const string Cactus_outer_top_right = "cactus-outer-top-right";
		public const string Cactus_right_side = "cactus-right-side";
		public const string Cloud_00 = "cloud-00";
		public const string Cloud_01 = "cloud-01";
		public const string Cloud_10 = "cloud-10";
		public const string Cloud_11 = "cloud-11";
		public const string Cloud_20 = "cloud-20";
		public const string Cloud_21 = "cloud-21";
		public const string Cloud_flower = "cloud-flower";
		public const string Cloud_mushroom = "cloud-mushroom";
		public const string Cloud_star = "cloud-star";
		public const string End_background = "end-background";
		public const string End_barrier = "end-barrier";
		public const string End_cactus_left_side = "end-cactus-left-side";
		public const string End_cactus_right_side = "end-cactus-right-side";
		public const string End_cactus_top_left = "end-cactus-top-left";
		public const string End_cactus_top_right = "end-cactus-top-right";
		public const string End_portal_bot_left = "end-portal-bot-left";
		public const string End_portal_bot_mid = "end-portal-bot-mid";
		public const string End_portal_bot_right = "end-portal-bot-right";
		public const string End_portal_mid_left = "end-portal-mid-left";
		public const string End_portal_mid_mid = "end-portal-mid-mid";
		public const string End_portal_mid_right = "end-portal-mid-right";
		public const string End_portal_top_left = "end-portal-top-left";
		public const string End_portal_top_mid = "end-portal-top-mid";
		public const string End_portal_top_right = "end-portal-top-right";
		public const string Independent_platform = "independent-platform";
		public const string Inner_cactus_top_left = "inner-cactus-top-left";
		public const string Inner_cactus_top_right = "inner-cactus-top-right";
		public const string Pink_bot_left = "pink-bot-left";
		public const string Pink_bot_mid = "pink-bot-mid";
		public const string Pink_bot_right = "pink-bot-right";
		public const string Pink_mid_left = "pink-mid-left";
		public const string Pink_mid_mid = "pink-mid-mid";
		public const string Pink_mid_right = "pink-mid-right";
		public const string Pink_shade_bot = "pink-shade-bot";
		public const string Pink_shade_mid = "pink-shade-mid";
		public const string Pink_shade_top = "pink-shade-top";
		public const string Pink_top_left = "pink-top-left";
		public const string Pink_top_mid = "pink-top-mid";
		public const string Pink_top_right = "pink-top-right";
		public const string Pipe_bot_left = "pipe-bot-left";
		public const string Pipe_bot_right = "pipe-bot-right";
		public const string Pipe_top_left = "pipe-top-left";
		public const string Pipe_top_right = "pipe-top-right";
		public const string Platform_bot_left = "platform-bot-left";
		public const string Platform_bot_mid = "platform-bot-mid";
		public const string Platform_bot_right = "platform-bot-right";
		public const string Platform_top_left = "platform-top-left";
		public const string Platform_top_mid = "platform-top-mid";
		public const string Platform_top_right = "platform-top-right";
		public const string Shade_bot_left = "shade-bot-left";
		public const string Shade_left = "shade-left";
		public const string Shade_top_left = "shade-top-left";
		public const string Shade_top_right = "shade-top-right";
		public const string Shade_top = "shade-top";
		public const string Sky_platform = "sky-platform";
		public const string White_bot_left = "white-bot-left";
		public const string White_bot_mid = "white-bot-mid";
		public const string White_bot_right = "white-bot-right";
		public const string White_mid_left = "white-mid-left";
		public const string White_mid_mid = "white-mid-mid";
		public const string White_mid_right = "white-mid-right";
		public const string White_shade_bot = "white-shade-bot";
		public const string White_shade_mid = "white-shade-mid";
		public const string White_shade_top = "white-shade-top";
		public const string White_top_left = "white-top-left";
		public const string White_top_mid = "white-top-mid";
		public const string White_top_right = "white-top-right";
	}
}