/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:40c6dd82acd14273f42248ad1f967a19:2392a98fa9e9f21130635efff3631102:03ba1ffa054b4dee5dce9e75d4f127e8$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Green_plant_up_left_closed = "green-plant-up-left-closed";
		public const string Green_plant_up_left_open = "green-plant-up-left-open";
	}
}