/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:f6153a91a882bbfb0f1e6a49b356c6d5:16c5ce157f45d4875b4d2a25d2e67ef5:9cebe17147c3601f75208ae8f1c05a3b$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Green_plant_down_left_closed = "green-plant-down-left-closed";
		public const string Green_plant_down_left_open = "green-plant-down-left-open";
	}
}