/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c8ecba00dc1bbf43b90ad41df726294d:f3d92b47007d3b51104c0fd9d778aabf:e9acb67dd260c682fa48df4df870a0d1$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Green_plant_bite_1 = "green-plant-bite-1";
		public const string Green_plant_bite_2 = "green-plant-bite-2";
	}
}