/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:cf41552d2f17900b409d89fdc12eec64:cef84b147c619daa775c19a422eec66b:0c2f8eb5f05c17f39f0585d4e174e8c8$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Projectile_1 = "projectile-1";
		public const string Projectile_2 = "projectile-2";
		public const string Projectile_3 = "projectile-3";
		public const string Projectile_4 = "projectile-4";
	}
}