/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:6e823715d730f43c092474c803dc5ffa:fcbb3509b5ff425060e0680c26e0176d:966815ed0a6ac2fa9616dbe33b195680$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Red_plant_up_left_closed = "red-plant-up-left-closed";
		public const string Red_plant_up_left_open = "red-plant-up-left-open";
	}
}