/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:881ed2922412a06dc27aaed6153df7b4:b291698599c0bc0b4099e7399490383b:01223f6dbbf47221308476b2c413b574$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Red_plant_down_left_closed = "red-plant-down-left-closed";
		public const string Red_plant_down_left_open = "red-plant-down-left-open";
	}
}